# makefile configuration
COMMON_OBJECTS	=
CPU		= msp430g2553
CFLAGS		= -mmcu=${CPU} -I../h
LDFLAGS		= L/opt/ti.msp430_gcc/include

CC		= msp430-elf-gcc
AS		= msp430-elf-as

all: toy.elf

toy.elf: ${COMMON_OBJECTS} p1_interrupt_handler.o led.o switches.o toyMain.o libTimer.a
	${CC} ${CFLAGS} ${LDFLAGS} -o $a $^


load: toy.elf
	msp430loader.sh toy.elf


clean:
	rm -f *.o *.elf
